### ISSUE TITLE
Unicode variables?

### ISSUE THREAD

**Issue by jackrusher** [yetanalytics/flint#23]
(Thanks for this library, it has saved me a good bit of work!)

The documentation mentions that:

> For simplicity, many terms in Flint only allow a subset of the characters that the SPARQL spec allows. For example, the latter often accepts Unicode characters, while Flint is ASCII-only outside of IRIs or string literals.

This is quite awkward for programmers working in non-English languages. Any chance we could expand charset support for variable names in particular?

**Comment by kelvinqian00** [comment]
Thanks for the response. Currently I am busy with several other tasks so it's unlikely that this will be added in the immediate future, but now that I am aware of the demand Unicode support will be high on my TODO list for Flint.
